language: java
jdk:
 - oraclejdk8

services:
 - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wodss_tippspiel;'

install: true

notifications:
  email: false
  slack: fhnw-wodss:2eK9ca6usY3orK9hBDdV8vvA
